name: high_hat
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  cloud_firestore: ^1.0.6
  cloud_functions: ^1.0.3

  firebase_analytics: ^8.0.1
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  flutter:
    sdk: flutter
  flutter_markdown: any
  flutter_signin_button: ^2.0.0-nullsafety.0
  flutter_svg: ^0.21.0+1

  google_sign_in: ^5.0.2

  intl: ^0.17.0

  ntp: ^2.0.0

  package_info: ^2.0.0
  provider: ^5.0.0

  sign_in_with_apple: ^3.0.0
  
  table_calendar: ^3.0.0
  twitter_login: ^4.0.1

dev_dependencies:
  build_runner: ^1.12.2

  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.5+1
  flutter_test:
    sdk: flutter

  pedantic_mono: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/schedule_app_icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - circle.svg
    - cross.svg
    - triangle.svg
    - schedule_icon_transparent.png
    - schedule_app_icon.png
    - terms_of_use.md
    - privacy_policy.md

flutter_native_splash:
  color: "#f8f8ff"
  image: "assets/schedule_icon_transparent.png"